unixmonkey/learngit

- feierabend.md
- the-very-new-file
Y is really cool everybody wants to have it, Y not?
> (#123) Add function X to make it behave like Y

- doc.txt
- newFile
This patch adds the critical funcionality xy that  we neet to solve
issue abc
> (TR-989089) Add functionality xy

- master_of_puppets.txt
- the-new-file
Functionality x provides feature requested in TR666666
> (#TR01234567) Add functionality x

- This-is-test.txt
- new_file.txt
This patch x adds the critical functionality that we need to meet our
project goals. It has been testing on platform y and z
> (DSS-1234)  Add functionality x

- This-is-test.txt
- mynewfile.txt
- test.txt
(Why should this be merged?) This a the very critical new functionality
that everybody's been waiting for. It allows to fly to Mars with an
FTL drive spaceship.. or something
> (#myticketnumber-12345) Add new functionality X  to  do something

- FTLdrive-instructions.txt
- mynewfile.txt
We don't want anybody to read our secret things online
> (Starfleetid-27831) remove secret FTL instructions

- the-very-new-file
Nobody ever used it so its obsolete.
> (124) Remove feature x

- new_file.txt
The file was really cool but also useless. Go away!
> (DSS-2345) Remove useless file

- test.txt
> (#0123210) Adding new test for functionality X

- tea.md
suggesting an alternative beverage
> (#546) start drinking Tea

- feierabend.md
> 42_add_beer

- This-is-test.txt
Awsome text file. I want to be promoted to a top manager now!
> (DSS_3456) Add a third line to indicate this is the mother of cool files

- master_of_puppets.txt
- newFile
> (TR 321313)  Delete files

- all_the_things.txt
- stuff.md
> Add all the things

- feierabend.md
- foo_feature.md
The new feature foo helps you getting more out of learngit.
Rather than using the initial feierabned, you can now use a
native Bavarian one.
> (#1234) Add feature foo

- cricket.md
- tea.md
This is a long description of stuff and things
Well actually not that long as i am bored
It is the why it has changed not what has changed.
> (#12345) Add feature stuff

- doc.txt
Modifications done during the Puppet Training
> (#1234) Add feature foo, modify doc.txt

- howstheweather
- testfile
This is extra stuff for how is the weather  and the testfile that was
created.
> (#TicketNumber) Add testfile and update weather

- newest-feature.txt
Feature of such awesomeness no distro can do without
> (124816) add new feature

- all_the_things.txt
- memory_pressure
Without this patch, one cannot do the basics of this program on osx.
> (PUP-1234) Add functionality foo

- meow.txt
I wanted to try deleting something
> (new ticket) kill he cat

- README_ARNOLDC.md
Adding README file from Arnold C because it's hilarious
> (PUP-12345) Add README for Arnold C language

- ers-file.txt
- test.txt
This is the long winded explanation of the changes.
> Added ers-file and added Trump to test.txt
